"""empty message

Revision ID: 1beac2f5d2d3
Revises: 3e96e86fb42f
Create Date: 2022-07-05 23:17:13.633573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1beac2f5d2d3'
down_revision = '3e96e86fb42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('nights', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'nights')
    # ### end Alembic commands ###
