"""No more country needed

Revision ID: 49e36e315377
Revises: bd3784c7e1d4
Create Date: 2022-06-13 15:26:12.624045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e36e315377'
down_revision = 'bd3784c7e1d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
