"""first migration

Revision ID: 6170ecc81da6
Revises: 
Create Date: 2022-06-16 16:25:06.439713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6170ecc81da6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('spot_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('check_in', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('check_out', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['spot_id'], ['spots.id'], name='bookings_spot_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bookings_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='bookings_pkey')
    )
    # ### end Alembic commands ###
