"""remove image req

Revision ID: cb026ee0299e
Revises: 49e36e315377
Create Date: 2022-06-14 05:13:21.853832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb026ee0299e'
down_revision = '49e36e315377'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
